//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task2.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Task2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Button_Confirm {
            get {
                return ResourceManager.GetString("Button_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Button_Create {
            get {
                return ResourceManager.GetString("Button_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Button_Delete {
            get {
                return ResourceManager.GetString("Button_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Button_Update {
            get {
                return ResourceManager.GetString("Button_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        public static string ColumnHeader_Age {
            get {
                return ResourceManager.GetString("ColumnHeader_Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string ColumnHeader_FullName {
            get {
                return ResourceManager.GetString("ColumnHeader_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hire Date.
        /// </summary>
        public static string ColumnHeader_HireDate {
            get {
                return ResourceManager.GetString("ColumnHeader_HireDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string ColumnHeader_Id {
            get {
                return ResourceManager.GetString("ColumnHeader_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Married.
        /// </summary>
        public static string ColumnHeader_IsMarried {
            get {
                return ResourceManager.GetString("ColumnHeader_IsMarried", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string ColumnHeader_Position {
            get {
                return ResourceManager.GetString("ColumnHeader_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary.
        /// </summary>
        public static string ColumnHeader_Salary {
            get {
                return ResourceManager.GetString("ColumnHeader_Salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Confirmation.
        /// </summary>
        public static string Header_DeleteConfirmation {
            get {
                return ResourceManager.GetString("Header_DeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate IDs Found.
        /// </summary>
        public static string Header_DuplicatedId {
            get {
                return ResourceManager.GetString("Header_DuplicatedId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Header_Error {
            get {
                return ResourceManager.GetString("Header_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Cancelled.
        /// </summary>
        public static string Header_ImportCancelled {
            get {
                return ResourceManager.GetString("Header_ImportCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shrink Records.
        /// </summary>
        public static string Header_ShrinkRecords {
            get {
                return ResourceManager.GetString("Header_ShrinkRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation Error.
        /// </summary>
        public static string Header_ValidationError {
            get {
                return ResourceManager.GetString("Header_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        public static string Label_Age {
            get {
                return ResourceManager.GetString("Label_Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string Label_FullName {
            get {
                return ResourceManager.GetString("Label_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hire Date.
        /// </summary>
        public static string Label_HireDate {
            get {
                return ResourceManager.GetString("Label_HireDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Married.
        /// </summary>
        public static string Label_Married {
            get {
                return ResourceManager.GetString("Label_Married", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string Label_Position {
            get {
                return ResourceManager.GetString("Label_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary.
        /// </summary>
        public static string Label_Salary {
            get {
                return ResourceManager.GetString("Label_Salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string MenuOption_File {
            get {
                return ResourceManager.GetString("MenuOption_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string MenuOption_Open {
            get {
                return ResourceManager.GetString("MenuOption_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string MenuOption_Save {
            get {
                return ResourceManager.GetString("MenuOption_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete &apos;{0}&apos; (id = {1})?.
        /// </summary>
        public static string Message_DeleteConfirmation {
            get {
                return ResourceManager.GetString("Message_DeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file contains the following Id duplicates:
        ///{0}
        ///
        ///Keep the first occurrence of each duplicate and ignore the rest?.
        /// </summary>
        public static string Message_DuplicateIds {
            get {
                return ResourceManager.GetString("Message_DuplicateIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter valid data.
        /// </summary>
        public static string Message_EnterValidData {
            get {
                return ResourceManager.GetString("Message_EnterValidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export failed: {0}.
        /// </summary>
        public static string Message_ExportFailed {
            get {
                return ResourceManager.GetString("Message_ExportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import cancelled. Please, fix the file and try again.
        /// </summary>
        public static string Message_ImportCancelled {
            get {
                return ResourceManager.GetString("Message_ImportCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have set a record limit lower than the number of records currently loaded. Do you want to trim the list?.
        /// </summary>
        public static string Message_ImportedMoreThanLimit {
            get {
                return ResourceManager.GetString("Message_ImportedMoreThanLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import failed: {0}.
        /// </summary>
        public static string Message_ImportFailed {
            get {
                return ResourceManager.GetString("Message_ImportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum record count must be greater than 0.
        /// </summary>
        public static string Message_MaxRecordsCount {
            get {
                return ResourceManager.GetString("Message_MaxRecordsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file contains too many records (check out settings).
        /// </summary>
        public static string Message_TooManyRecords {
            get {
                return ResourceManager.GetString("Message_TooManyRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max records.
        /// </summary>
        public static string Settings_MaxRecords {
            get {
                return ResourceManager.GetString("Settings_MaxRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Settings_Theme {
            get {
                return ResourceManager.GetString("Settings_Theme", resourceCulture);
            }
        }
    }
}
